# Generated by Django 4.2 on 2023-04-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('archived', models.BooleanField()),
                ('private', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('content', models.JSONField()),
            ],
        ),
    ]
