# Generated by Django 4.2 on 2023-04-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.TextField(primary_key=True, serialize=False)),
                ('place_type', models.CharField(default='general', max_length=255)),
                ('place_x_coordinate', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('place_y_coordinate', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('place_google_link', models.CharField(default='https://goo.gl/maps/6N5kYyXZWXFNiivE7', max_length=512)),
                ('place_json_info', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaceToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('place_id', models.IntegerField()),
            ],
            options={
                'unique_together': {('uid', 'place_id')},
            },
        ),
        migrations.DeleteModel(
            name='ItineraryCollaborationPermission',
        ),
    ]
