# Generated by Django 4.2 on 2023-04-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='content',
            new_name='itinerary',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='city',
            field=models.CharField(default='PLACEHOLDER_CITY', max_length=255),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='country',
            field=models.CharField(default='PLACEHOLDER_COUNTRY', max_length=255),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='est_budget_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='est_budget_up',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='state',
            field=models.CharField(default='PLACEHOLDER_STATE', max_length=255),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='title',
            field=models.CharField(default='PLACEHOLDER_TITLE', max_length=255),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
