# Generated by Django 4.2 on 2023-04-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
