# Generated by Django 4.2 on 2023-04-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_place_placetouser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='place_json_info',
            new_name='place_google_json',
        ),
        migrations.RemoveField(
            model_name='place',
            name='place_google_link',
        ),
        migrations.RemoveField(
            model_name='place',
            name='place_x_coordinate',
        ),
        migrations.RemoveField(
            model_name='place',
            name='place_y_coordinate',
        ),
        migrations.AddField(
            model_name='place',
            name='place_id_google',
            field=models.CharField(default=None, max_length=127),
        ),
        migrations.AddField(
            model_name='place',
            name='place_lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='place',
            name='place_lng',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='placetouser',
            name='name',
            field=models.CharField(default=None, max_length=127),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
