# Generated by Django 4.2 on 2023-04-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_rename_content_itinerary_itinerary_itinerary_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryPermission',
            fields=[
                ('user_itin_pair_id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('tid', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='itinerary',
            old_name='uid',
            new_name='created_by',
        ),
    ]
