# Generated by Django 4.2 on 2023-04-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0003_itinerarypermission_rename_uid_itinerary_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='description',
            field=models.CharField(default='Untitiled', max_length=255),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='title',
            field=models.CharField(default='Untitiled', max_length=255),
        ),
    ]
