# Generated by Django 4.2 on 2023-04-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0004_itinerary_description_alter_itinerary_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='description',
            field=models.CharField(default='This itinerary does not have a description yet...', max_length=1024),
        ),
    ]
