# Generated by Django 4.2 on 2023-04-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0009_alter_place_place_id_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id_google',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
