# Generated by Django 4.2 on 2023-04-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0011_alter_place_place_id_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placetouser',
            name='name',
            field=models.CharField(default='Untitled Place', max_length=127),
        ),
    ]
