# Generated by Django 4.2 on 2023-04-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0012_alter_placetouser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_lng',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
        ),
    ]
