# Generated by Django 4.2 on 2023-04-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0013_alter_place_place_lat_alter_place_place_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_lat',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_lng',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=20),
        ),
    ]
